n1 = input("Digite um numero: ")
print(type(n1))
print("E um numero:",n1.isnumeric())
print("E alphanumerico:",n1.isalnum())
print("E alfabetico:",n1.isalpha())
print("E um digito:",n1.isdigit())
print("E um decimal:",n1.isdecimal())
print("E um espaco:",n1.isspace())
print("E UPPERCASE",n1.isupper())
print("E lowercase",n1.islower())